export const RECEIVE_CHANNEL = 'RECEIVE_CHANNEL';

export const UPDATE_CHANNEL = 'UPDATE_CHANNEL';

export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';

export const UPDATE_MESSAGE = 'UPDATE_MESSAGE';

export const UPDATE_CURRENT_CHANNEL = 'UPDATE_CURRENT_CHANNEL';
