export const RECEIVE_CHANNEL = 'RECEIVE_CHANNEL';

export const UPDATE_CHANNEL = 'UPDATE_CHANNEL';

export const UPDATE_MESSAGE = 'UPDATE_MESSAGE';

export const UPDATE_CURRENT_CHANNEL = 'UPDATE_CURRENT_CHANNEL';

export const RECEIVE_CHANNEL_MESSAGE = 'RECEIVE_CHANNEL_MESSAGE';

export const RECEIVE_CHAT_MESSAGE = 'RECEIVE_CHAT_MESSAGE';

export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
